config/routes.rb
require 'leaves'

module Laurels
  module RouteConstraints
    class HTMLRequest
      def self.matches?(request)
        request.accept =~ /html/
      end
    end
  end
end

Laurels::Application.routes.draw do

  match "landing", :to => 'welcome#index'

  constraints(Laurels::RouteConstraints::HTMLRequest) do
    match "/", :to => 'welcome#leaves', :constraints => { :subdomain => 'leaves' }
  end
  mount Leaves::Server, :at => "/", :constraints => { :subdomain => 'leaves' }

  root :to => 'welcome#marketing'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  if Rails.env.production?
    http_basic_authenticate_with name: ENV['HTTP_USERNAME'], password: ENV['HTTP_PASSWORD'], :except => :marketing
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def leaves
    render :layout => 'application'
  end

  def marketing
    response.headers['Cache-Control'] = "public, must-revalidate, max-age=#{1.day.seconds}"
    render :layout => 'marketing'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include UrlHelper
end

app/helpers/url_helper.rb
module UrlHelper
  def with_subdomain(subdomain)
    subdomain = (subdomain || "")
    subdomain += "." unless subdomain.empty?
    [subdomain, request.domain].join
  end

  def url_for(options = nil)
    if options.kind_of?(Hash) && options.has_key?(:subdomain)
      options[:host] = with_subdomain(options.delete(:subdomain))
    end
    super
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
    <div class="row">
      <div class="span3">
        <dl>
          <dt>Laurels</dt>
          <dd><%= link_to "Leaves", root_url(:subdomain => "leaves") %></dd>
          <dd><a href="#">Olive (Coming Soon)</a></dd>
          <dd><a href="#">Grapevine (Coming Soon)</a></dd>
        </dl>
      </div>
      <div class="span6 offset1">
        <dl>
          <dt>Papers</dt>
          <dd><%=link_to "Architectural Styles and the Design of Network-based Software Architectures".html_safe, "http://www.ics.uci.edu/~fielding/pubs/dissertation/top.htm" %></dd>
        </dl>
        <dl>
          <dt>People</dt>
          <dd><%=link_to "amundsen.com", "http://www.amundsen.com" %></dd>
          <dd><%=link_to "subbu.org", "http://www.subbu.org" %></dd>
          <dd><%=link_to "iansrobinson.com", "http://iansrobinson.com" %></dd>
          <dd><%=link_to "jim.webber.name", "http://jim.webber.name" %></dd>
        </dl>
        <dl>
          <dt>Books</dt>
          <dd><%=link_to "REST in Practice", "http://restinpractice.com/default.aspx" %></dd>
          <dd><%=link_to "Get Some REST (Coming Soon)", "http://getsomere.st/" %></dd>
          <dd><%=link_to "RESTful Web Services", "http://shop.oreilly.com/product/9780596529260.do" %></dd>
          <dd><%=link_to "RESTful Web Services Cookbook", "http://shop.oreilly.com/product/9780596801694.do" %></dd>
        </dl>
      </div>
      <div class="span5 offset1">
        <dl>
          <dt>Contribute</dt>
          <dd><a href="http://github.com/scudco/laurels">Fork on GitHub</a></dd>
          <dd>
            <a href="https://twitter.com/laurelsapp" class="twitter-follow-button" data-show-count="false" data-link-color="#FFFFFF">Follow @laurelsapp</a>
          </dd>
        </dl>
        <dl>
          <dt>Legal Nonsense</dt>
          <dd>
            <a rel="license" href="http://creativecommons.org/licenses/by/3.0/"><img alt="Creative Commons License" style="border-width:0" src="http://i.creativecommons.org/l/by/3.0/88x31.png" /></a>
          </dd>
        </dl>
      </div>
    </div>
  </div>
</footer>
<%= javascript_include_tag "application" %>
<script src="https://platform.twitter.com/widgets.js" type="text/javascript"></script>
<%= render 'layouts/google_analytics' %>

app/views/layouts/_google_analytics.html.erb
<% if Rails.env.production? %>
  <script type="text/javascript">

    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-26092803-1']);
    _gaq.push(['_setDomainName', '.laurelsapp.com']);
    _gaq.push(['_trackPageview']);

    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();

  </script>
<% end %>

app/views/layouts/_head.html.erb
<meta charset="utf-8" />
<title>Laurels</title>
<%= favicon_link_tag %>
<link href="//fonts.googleapis.com/css?family=Pacifico" rel="stylesheet" type="text/css">
<%= stylesheet_link_tag "application" %>
<%= csrf_meta_tags %>

app/views/layouts/_masthead.html.erb
<div class="masthead">
  <div class="container">
    <div class="row">
      <div class="span16">
        <h1>Laurels <small>REST by example</small></h1>
        <ul class="unstyled">
          <li>Explore working APIs</li>
          <li>Demystify HTTP and hypermedia</li>
          <li>Learn how to create RESTful clients</li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_topbar.html.erb
<div class="topbar">
  <div class="topbar-inner">
    <div class="container">
      <%= link_to "Laurels", landing_url(:subdomain => false), :class => 'brand' %>
      <ul class="nav">
        <li><%= link_to "Examples", root_path(:anchor => "examples") %></li>
        <li><%= link_to "Contribute", root_path(:anchor => "contribute") %></li>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= render "layouts/head" %>
  </head>
  <body>
    <%= render "layouts/topbar" %>
    <%= yield %>
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/layouts/marketing.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="description" content="An tool to teach the concepts of REST through a series of API exercises." />
    <title>Laurels - REST by Example</title>
    <%= favicon_link_tag %>
    <link href="http://fonts.googleapis.com/css?family=Pacifico" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="//twitter.github.com/bootstrap/1.4.0/bootstrap.min.css">
    <link rel="stylesheet" href="/slimbox/css/slimbox2.css">
    <style>
      html {
        background: #f5f2e1 url(<%= asset_path('laurels-large-transparent.png') %>) no-repeat 50% 50px;
      }

      body {
        height: 100%;
        background-color: transparent;
      }

      .logo {
        font-family: "Pacifico", cursive;
      }

      .marketing {
        width: 520px;
        margin: 280px auto;
        text-align: center;
      }

      .marketing h1 {
        font-size: 72px;
        line-height: 36px;
      }

      .marketing h1 small {
        font-size: 24px;
        line-height: 36px;
      }

      .marketing #email-form-success {
        width: 400px;
        margin: 30px auto;
      }
    </style>

    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="marketing">
      <%= yield %>
    </div>
    <%= render 'layouts/google_analytics' %>
    <script src="/slimbox/js/slimbox2.js"></script>
  </body>
</html>

app/views/layouts/welcome.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= render "layouts/head" %>
  </head>
  <body>

    <%= render "layouts/topbar" %>
    <%= render "layouts/masthead" %>
    <div id="content">
      <%= yield %>
      <%= render "layouts/footer" %>
    </div>

  </body>
</html>

app/views/welcome/index.html.erb
<div class="container">
  <div id="examples" class="row">
    <h2>Examples</h2>
    <div class="span-one-third">
      <div class="laurel">
        <%= image_tag "leaves-icon.png", :width => 100, :height => 100 %>
        <h3>Leaves</h3>
        <p>
          Contact Manager
        </p>
        <%= link_to "GET started", root_url(:subdomain => 'leaves'), :class => "btn" %>
      </div>
    </div>
    <div class="span-one-third">
      <div class="laurel">
        <%= image_tag "olive-icon.png", :width => 100, :height => 100 %>
        <h3>Olive</h3>
        <p>
          Cocktail Library
        </p>
        <a href="#" class="btn disabled">Coming Soon</a>
      </div>
    </div>
    <div class="span-one-third">
      <div class="laurel">
        <%= image_tag "grapes-icon.png", :width => 100, :height => 100 %>
        <h3>Grapevine</h3>
        <p>
          Social Network
        </p>
        <a href="#" class="btn disabled">Coming Soon</a>
      </div>
    </div>
  </div>
  <div id="contribute" class="row">
    <h2>Contribute</h2>
    <div class="span8">
      <p>
        A <span class="logo">laurel</span> is a web service meant
        to demonstrate and teach particular aspects of RESTful
        architecture. You can write your own RESTful web service
        and submit it to this site.
      </p>
      <p>
        Though pragmatism is valued in each laurel (as
        demonstrated in the requirement for a JSON parseable
        response), it is not the goal of the <span
          class="logo">Laurels</span> project. It is <em>REST by
          example</em>. It is beneficial to know the limitations of
        clients consuming RESTful services. Browsers, JavaScript
        frameworks, and HTTP libraries all have quirks. <span
          class="logo">Laurels</span> can help highlight these
        shortcomings by providing real, working RESTful web
        services.
      </p>
      <a href="#" class="btn large primary">Submit Your Laurel</a>
    </div>
    <div class="span8">
      <ul>
        <li>Should be focused on a single problem</li>
        <li>Must be HTTP-based and implement correct headers, verbs, and response codes</li>
        <li>Must accept requests for <code>application/json</code> or any JSON vendor subset</li>
        <li>May accept requests for other MIME types</li>
        <li>Should not require any form of authentication unless it is to demonstrate an aspect of REST</li>
        <li>Must provide API documentation consisting of:
          <ul>
            <li>general description of the service</li>
            <li>an entry URI</li>
            <li>acceptable media type(s)</li>
            <li>a list of resource types</li>
            <li>a list of relation definitions</li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/welcome/leaves.html.erb
<div id="leaves" class="first container">
  <h1 class="leaves-logo">Leaves <small>Contact Manager</small></h1>
  <div class="row">
    <ul class="tabs" data-tabs="tabs">
      <li class="active"><a href="#console">HTTP Console</a></li>
      <li><a href="#documentation">Documentation</a></li>
      <li><a href="#exercises">Exercises</a></li>
    </ul>
  </div>
  <div class="tab-content">
    <div id="console" class="active http-console">
    </div>

    <div id="documentation">
      <h2>Documentation</h2>
      <div class="row">
        <div class="span8">
          <h3>Entry Point</h3>
          <p>↳ http://leaves.laurels.com/ <button class="btn small primary">Launch HTTP console &raquo;</button></p>
        </div>

        <div class="span8">
          <h3>Media Type</h3>
          <p>application/vnd.laurels.leaves+json</p>
        </div>
      </div>

      <div class="row">
        <div class="span8">
          <h3>Resources</h3>
          <table>
            <thead>
              <tr>
                <th>Resource</th>
                <th>Description</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>contacts</td>
                <td>All the contacts stored in Leaves</td>
              </tr>
              <tr>
                <td>contact</td>
                <td>An individual contact</td>
              </tr>
            </tbody>
            <tfoot></tfoot>
          </table>
        </div>

        <div class="span8">
          <h3>Link Relations</h3>
          <table>
            <thead>
              <tr>
                <th><code>rel</code></th>
                <th>Description</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td><a href="/rels/map">/rels/map</a></td>
                <td>A map of a contact's address</td>
              </tr>
            </tbody>
            <tfoot></tfoot>
          </table>
        </div>
      </div>
    </div>

    <div id="exercises" class="row">
      <div class="span16">
        <h2>Exercises</h2>
        <h3>Create a Contact</h3>
        <ol>
          <li>Find the link specifying the contacts resource</li>
          <li>Determine the correct HTTP method to create a new contact</li>
          <li>
            Send the following parameters along with your request:
            <dl>
              <dt>Name</dt>
              <dd>Roy Fielding</dd>
              <dt>Email</dt>
              <dd>not.actually.roys.email@laurels.com</dd>
            </dl>
          </li>
        </ol>
      </div>
    </div>
  </div>
</div>

app/views/welcome/marketing.html.erb
<h1><span class="logo">Laurels</span><br /><small>REST by example</small></h1>
<ul class="media-grid">
  <li>
    <%= link_to asset_path("landing.png"), :rel => "lightbox-examples" do %>
      <%= image_tag asset_path("landing-thumb.png"), :width => 150, :height => 90 %>
    <% end %>
  </li>
  <li>
    <%= link_to asset_path("http-console-1.png"), :rel => "lightbox-examples" do %>
      <%= image_tag asset_path("http-console-1-thumb.png"), :width => 150, :height => 90 %>
    <% end %>
  </li>
  <li>
    <%= link_to asset_path("http-console-2.png"), :rel => "lightbox-examples" do %>
      <%= image_tag asset_path("http-console-2-thumb.png"), :width => 150, :height => 90 %>
    <% end %>
  </li>
</ul>
<form id="email-form" target="form-handler" action="https://docs.google.com/spreadsheet/formResponse?formkey=dEhWZ2xUcjN1WVhLZGFnbmo0NEZ3bXc6MQ" method="POST">
  <h2>
    Get invited to participate in Laurels
  </h2>
  <input type="email" name="entry.0.single" placeholder="your@email.com" />
  <input type="submit" name="submit" class="btn success" value="submit" />
</form>
<div id="email-form-success" style="display:none;">
  <div class="alert-message notice">
    <p><strong>Thanks for your interest!</strong> <a href="https://twitter.com/laurelsapp">Follow @laurelsapp</a> to learn more.</p>
  </div>
  <a href="https://twitter.com/laurelsapp" class="twitter-follow-button" data-show-count="false" data-align="center" data-width="175px">Follow @laurelsapp</a>
  <script src="https://platform.twitter.com/widgets.js" type="text/javascript"></script>
</div>
<iframe id="form-handler" name="form-handler" style="width:0px; height:0px; border:0px;"></iframe>

<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.6.4/jquery.min.js"></script>
<script type="text/javascript">
  (function($) {
   $(function() {
     $('#email-form').submit(function(evt) {
       $(this).hide();
       $('#email-form-success').show();
       });
     });
   })(jQuery);
</script>